### ISSUE TITLE
Docker in docker

### ISSUE THREAD

**Issue by kkaiser** [acdha/pre-commit-docker#3]
Some pre-commit hooks that use docker won't work inside this docker image

Running this command
```bash
docker run --rm --volume "${PWD}":/code acdha/pre-commit:latest
```

With this `.pre-commit-config.yaml` config

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.3.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint-docker
      - id: markdownlint-fix-docker
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
```

Results in this output:

```text
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
markdownlint-docker......................................................Failed
- hook id: markdownlint-docker
- exit code: 1

Executable `docker` not found

markdownlint-fix-docker..................................................Failed
- hook id: markdownlint-fix-docker
- exit code: 1

Executable `docker` not found

Lint Dockerfiles.........................................................Failed
- hook id: hadolint-docker
- exit code: 1

Executable `docker` not found
```

I would very much prefer to avoid installing `hadolint` and `makrdownlint` on my host. Are you planning to support running docker in docker or is there a better workaround (two different configs or something similar)?
